### ISSUE TITLE
Adding works from Hard Drive

### ISSUE THREAD

**Issue by abadguy87** [AcrylicShrimp/dlsite-manager#10]
Can the manager display only works that you have on your account? Or can you point it to a folder with RJxx zip files that you don't have on your account and still display them? Thanks.

**Comment by AcrylicShrimp** [comment]
Yes, currently the manager can display works that you have. But the DLsite's API allows us to fetch works information without having them, so I think I can implement those features. I'll consider them to be shipped in next release.

**Comment by CuddleBear92** [comment]
Any update on this? DLSite manager from ULMF is dead in the water 
and Atlas (<https://github.com/KJNeko/Atlas>) is probably half a year out for DLSite support even though they have started scraping general data.

**Comment by AcrylicShrimp** [comment]
@CuddleBear92 DLsite Manager at this moment requires detailed product information which is only open to product owners. I'm re-designing entire codebase to support products with incomplete information. But I was very busy end of 2023 and earlier 2024, the work is not much progressed. Now I'm back, I think next release will be completed within a month at the latest.

**Comment by CuddleBear92** [comment]
what kind of detailed info is required that only the product owners has? seems most of the info outside of the main description is in their json open for all, even games that is removed from the store, heck they still host all the product images from removed products to this day. https://www.dlsite.com/maniax/product/info/ajax?product_id=RJ021041

Not that DLsite Manager currently pulls the description, the only thing i can see the client has that the json is missing is the creator name which could be pulled from the maker list url that lists all the creators. such a thing could just have a maker_id <-> creator name map. 
Or i guess just looking it up on a per  maker_id type deal in html. 

Not quite sure if they have a public json for the creator. 
Just an idea anyway.

**Comment by AcrylicShrimp** [comment]
@CuddleBear92 For an example, DLsite Manager requires file list to download. It must be fetched and stored to local database in current implementation. Yes, technically they are not needed to support the feature this issue suggests, but anyway, those behavior must be changed, that's the point.

**Comment by AcrylicShrimp** [comment]
Added in the latest release.
