### ISSUE TITLE
Comic downloads not working

### ISSUE THREAD

**Issue by lenzdz** [AcrylicShrimp/dlsite-manager#26]
Hey!

I'm trying to download a comic, but the program isn't working properly. I click the download button and that creates a folder where the images should be, but when opening it, I only find a text file. 

![Captura de pantalla 2024-09-22 220016](https://github.com/user-attachments/assets/5ace12a5-a2ed-4353-a5bb-cd04be0ecb87)

Other downloader apps are having the same issue, so I'm guessing perhaps the site's structure changed and that's why apps aren't able to fetch correctly.

Thanks in advance!

**Comment by AcrylicShrimp** [comment]
Duplicated, let's discuss it in #8
