### ISSUE TITLE
db files not saving properly? 

### ISSUE THREAD

**Issue by CuddleBear92** [AcrylicShrimp/dlsite-manager#5]
I don't think the db files are saving properly as its never writing to the main db files but leave it in the wal and shm file which is supposed to be temp files.

I am not 100% certain but my db so far has gotten corrupted once after a crash so it wouldn't boot anymore, also it has lost its install states for the titles that it has downloaded, thinking they are not downloaded and its its folders.
This was on two different databases so far.

It shouldn't be saved like this i believe. 
![image](https://github.com/AcrylicShrimp/dlsite-manager/assets/8496821/3d7f937b-8e1a-4282-9a00-499c194f42fb)

Side note, why are these not next to the exe for a portable install?

**Comment by AcrylicShrimp** [comment]
Thank for reporting! I didn't even noticed that. I think there're some problems or bugs in database integration module I wrote. Let me investigate it.

And it seems that you lost all of your data. Accounts and product data is relatively easy to restore, but I don't think there is a way to load previously installed product data currently.

So here's my plan. First I'll add installation restoration feature ASAP to cover your problem. After it released, I should investigate and fix that database problems.

**Comment by CuddleBear92** [comment]
sounds good. yeah, the install state has been a constant after testing your client for a few days. it doesn't keep it and there is no way to scan the folder to see what's already there. a scan feature would be great. a bonus for that would be to grab metadata on titles you don't own legally aswell as its just metadata. 
just nuking the db has not been a huge issue really. only have 80 titles on DLSite so its not too much at all.

**Comment by AcrylicShrimp** [comment]
@CuddleBear92, I released a new version `1.5.0` to fix those. This release also includes a way to refresh product downloads too. You can access this action via `Product` > `Refresh Product Downloads` in top menu.

**Comment by CuddleBear92** [comment]
oh! thanks! closing the issue for now. checking it out in a minute!
