### ISSUE TITLE
a title fails to install/extract

### ISSUE THREAD

**Issue by CuddleBear92** [AcrylicShrimp/dlsite-manager#6]
So i have a single title in my library that fails to install or extract out of my 87 titles. that would be 
<https://www.dlsite.com/maniax/work/=/product_id/RJ01061277.html>

Unsure if this is cause its the last thing i bought or if its specifically this title.
It seems to complete the download then fail to extract it then delete the folder for the title as a whole.

**Comment by AcrylicShrimp** [comment]
After some testing, I found that the product was compressed with `deflate64` which is from Windows 11. I don't believe that I can support `deflate64` soon. Can you download it w/o decompression, and un-zip it with other software?

**Comment by AcrylicShrimp** [comment]
Maybe I have to fix the extraction logic; extraction failure must not lead to product download failure.

**Comment by CuddleBear92** [comment]
well 7zip and so on has no issues extracting these files. just a weird interaction that the client doesn't do the full download and install process on its own.

**Comment by AcrylicShrimp** [comment]
Sorry for late response, I missed your last comment in my mailbox. Yes, the `deflate64` definitely can be decompressed in some software, but please understand that I cannot implement all those decompression algorithms on my own. As you can see, this project uses other crates to decompress files, and there's no crate that supports `deflate64` even in 2024.

**Comment by ckaznable** [comment]
Try using [zip-rs/zip2](https://github.com/zip-rs/zip2) to decompress the deflate64 file.

**Comment by AcrylicShrimp** [comment]
Fixed in the latest release.
